name: Push Docker Image

on:
  push:
      branches: [ "main" ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v3

    - name: Log in to Docker registry
      uses: docker/login-action@v1
      with:
        registry: registry.hagn.network
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: registry.hagn.network/document-srv:latest
